#Configure SWAP files
---
- hosts: aws
  become: yes
  gather_facts: no
  vars_files:
    - ../vars/main.yml

  tasks:
  - name: 'Ensure basic packages are present'
    apt:
      update_cache: yes
      name: "{{ item }}"
    with_items:
        - "vim"
        - "figlet"

# Copy Rundeck Key