
#
#Installs passbolt in a container
#
---
- hosts: passbolt
  become: yes
  gather_facts: no

  tasks:
  - name: Create folder for source code
  	shell: mkdir /root/git

  - name: Download passbolt code from git
  	git:
  		repo: https://github.com/passbolt/passbolt.git
  		dest: /root/git



