---
- name: Ensure python have all the requirements
  hosts: new_machines
  become: yes
  gather_facts: no

  tasks:
  - name: 'Ensure basic python3 packages are installed'
    apt: name={{item}}
    cache_valid_time: 3600
    with_items:
        - python3
        - python3-pip
        - python-pip

  - name: 'Update pip to latest version'
    pip:
      name: pip

  - name: "Install virtualenvwrapper"
    import_role:
      name: lciolecki.virtualenvwrapper
    become: false
  